site_name: Mingxun Wang [dot] com

nav:
    - About Me: index.md
    - Research: research.md
    - Publications: publications.md
    - Music: music.md
    - Other: other.md
theme:
    name: material
    palette:
        primary: 'blue'
        accent: 'orange'

extra:
    social:
        - type: 'github'
          link: 'https://github.com/mwang87'
        - type: 'twitter'
          link: 'https://twitter.com/mingxunwang'

plugins:
    - search
    - git-revision-date-localized:
        type: datetime

markdown_extensions:
    - toc:
        permalink: true
    - admonition

extra:
  analytics:
    provider: google
    property: UA-15507025-1