site_name: Mingxun Wang [dot] com
nav:
    - About Me: index.md
    - Academics: academics.md
    - Music: music.md
    - Other: other.md
theme:
    name: material
    palette:
        primary: 'blue'
        accent: 'orange'
    logo:
        icon: 'person_pin'

extra:
    social:
        - type: 'github'
          link: 'https://github.com/mwang87'
        - type: 'twitter'
          link: 'https://twitter.com/mingxunwang'
plugins:
    - search
    - git-revision-date
google_analytics: ['UA-15507025-1', 'mingxunwang.com']
